# Change these first
owner: ocavue # Your GitHub username
repo: rino-status # Your GitHub repository name

# Add your sites here
sites:
  - name: Rino Homepage
    url: https://www.rino.app
  - name: Rino Web Application
    url: https://rino.app

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.rino.app
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Rino Status
  introTitle: "Rino Status"
  introMessage: ""
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: GitHub
      href: https://github.com/ocavue/rino
    - title: Twitter
      href: https://twitter.com/rino_editor

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
